# Generated by Django 5.1.1 on 2024-09-09 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='WRITE A UNIQUE CATEGORIES MAX lenght 256 symm', max_length=256, unique=True, verbose_name='title')),
                ('description', models.TextField(help_text='Something information about category', max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ExpectedPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Min symbols 0'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Max symbols 1000000000')], verbose_name='amount products')),
            ],
            options={
                'verbose_name': 'expected_products',
                'db_table': 'expected_products',
            },
        ),
        migrations.CreateModel(
            name='MailingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Not correct email')], verbose_name='email')),
            ],
            options={
                'verbose_name': 'mailing email',
                'db_table': 'mailing_email',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_for_sale', models.TextField(help_text='Max symbols 1000', max_length=1000, verbose_name='platform for sale')),
                ('amount_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Min symbols 0'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Max symbols 1000000000')], verbose_name='amount products')),
                ('damaged_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Min symbols 0'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Max symbols 1000000000')], verbose_name='amount damage products')),
            ],
            options={
                'verbose_name': 'purchased_products',
                'db_table': 'purchased_products',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='WRITE A UNIQUE CATEGORIES MAX lenght 256 symm', max_length=256, unique=True, verbose_name='title')),
                ('description', models.TextField(help_text='Something information about category', max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'subcategories',
                'db_table': 'subcategories',
            },
        ),
    ]
