# Generated by Django 5.1.1 on 2024-09-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='orders.categories', verbose_name='subcategories'),
        ),
        migrations.AddField(
            model_name='expectedpurchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_products', to='orders.product', verbose_name='Purchased Product'),
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='orders.product', verbose_name='PurchasedProduct'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='orders.categories', verbose_name='subcategories'),
        ),
    ]
