# Generated by Django 5.1.1 on 2024-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_article_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product', verbose_name='image'),
        ),
    ]
